# Generated by Django 4.2 on 2023-07-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_buyer',
            name='due_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='payments_seller',
            name='due_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
