# Generated by Django 4.2 on 2023-07-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_payments_buyer_due_date_payments_seller_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goats',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
