# Generated by Django 4.2 on 2023-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_goats_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='load_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
