# Generated by Django 4.2 on 2023-07-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_loads_load_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loads',
            name='load_id',
        ),
        migrations.AlterField(
            model_name='loads',
            name='id',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
