# Generated by Django 4.2 on 2023-07-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_loads_load_id_alter_loads_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='ref_num',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loads',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
