# Generated by Django 4.2 on 2023-07-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_loads_ref_num_alter_loads_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments_buyer',
            name='load',
        ),
        migrations.RemoveField(
            model_name='payments_seller',
            name='load',
        ),
    ]
