# Generated by Django 4.2 on 2023-07-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_payments_buyer_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='buyers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sellers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
