# Generated by Django 4.2 on 2023-07-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_agents_email_buyers_email_sellers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_buyer',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
